# image: registry.gitlab.com/truchas/ci-images:tpl-mpich-centos7-1.2.0
# image: gcc:9.3.0
# image: continuumio/anaconda3
image: python:latest

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/reference/pip_install/#caching
#
# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.
cache:
  paths:
    - .cache/pip
    - venv/

build_ep:
  stage: build
  script:
    - apt-get update
    - apt-get install -y gcc
    - apt-cache search fortran
    - gcc --version
    - pip install -U numpy
    - pip install -U scipy
    - pip install -U sphinx
    - pip install -U matplotlib
    - pip install -U pytest
    - pip install -U pytest-cov
    - pip install -U wxpython
    - python setup.py develop --user
  # artifacts:
  #   paths:
  #     - exactpack
  #     - doc

ep_tests:
  stage: test
  script:
    - pytest --junitxml=report.xml --cov=exactpack exactpack/tests/
    - coverage xml
  artifacts:
    when: always
    reports:
      junit: report.xml
      cobertura: coverage.xml

pages:
  stage: deploy
  script:
    - sphinx-build -b html doc/source public
  artifacts:
    paths:
      - public
  only:
    - master
